### ISSUE TITLE
AHC031にもalll_results.csvが欲しい

### ISSUE THREAD

**Issue by ansainbdg** [siman-man/ahc_statistics#1]
030/all_results.csvのような全参加者の全テストケースのスコアが見れるcsvがAHC031にもあると嬉しいです。もし追加される予定がないならその旨を教えていただけると嬉しいです。

**Comment by siman-man** [comment]
こちらのコミットで追加しました！

https://github.com/siman-man/ahc_statistics/commit/e962fae1d60f6ca78435fb35928d66e41d5b3b89

「毎回追加してたけど誰も使って無さそうだからしなくてもいいか」と思っていたら実は利用者がいることがわかったので、これからも追加するようにします 💪

**Comment by ansainbdg** [comment]
ありがとうございます。復習に使用します
